### ISSUE TITLE
is the data available?

### ISSUE THREAD

**Issue by andysingal** [onceuponai-dev/stories-fantasy-shop-assistant#1]
is the data available?

**Comment by qooba** [comment]
@andysingal - Here you have [data.yaml](https://github.com/onceuponai-dev/stories-fantasy-shop-assistant/blob/main/notebooks/data.yaml) to prepare delta table just got through `Prepare data` section in: [FantasyAssistantPrep.ipynb](https://github.com/onceuponai-dev/stories-fantasy-shop-assistant/blob/main/notebooks/FantasyAssistantPrep.ipynb)
